[package]
name = "crc24-openpgp-fast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc24 = "0.1.6"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "fast_vs_fallback"
harness = false
